#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-doRNG
Version  : 1.8.6.1
Release  : 79
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/doRNG_1.8.6.1.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/doRNG_1.8.6.1.tar.gz
Summary  : Generic Reproducible Parallel Backend for 'foreach' Loops
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-foreach
Requires: R-iterators
Requires: R-rngtools
BuildRequires : R-doParallel
BuildRequires : R-foreach
BuildRequires : R-iterators
BuildRequires : R-rngtools
BuildRequires : buildreq-R

%description
reproducible parallel foreach loops, using independent
    random streams as generated by L'Ecuyer's combined

%prep
%setup -q -n doRNG
pushd ..
cp -a doRNG buildavx2
popd
pushd ..
cp -a doRNG buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1736816604

%install
export SOURCE_DATE_EPOCH=1736816604
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/doRNG/DESCRIPTION
/usr/lib64/R/library/doRNG/INDEX
/usr/lib64/R/library/doRNG/Meta/Rd.rds
/usr/lib64/R/library/doRNG/Meta/demo.rds
/usr/lib64/R/library/doRNG/Meta/features.rds
/usr/lib64/R/library/doRNG/Meta/hsearch.rds
/usr/lib64/R/library/doRNG/Meta/links.rds
/usr/lib64/R/library/doRNG/Meta/nsInfo.rds
/usr/lib64/R/library/doRNG/Meta/package.rds
/usr/lib64/R/library/doRNG/Meta/vignette.rds
/usr/lib64/R/library/doRNG/NAMESPACE
/usr/lib64/R/library/doRNG/NEWS.md
/usr/lib64/R/library/doRNG/R/doRNG
/usr/lib64/R/library/doRNG/R/doRNG.rdb
/usr/lib64/R/library/doRNG/R/doRNG.rdx
/usr/lib64/R/library/doRNG/REFERENCES.bib
/usr/lib64/R/library/doRNG/demo/doRNG.R
/usr/lib64/R/library/doRNG/doc/doRNG.R
/usr/lib64/R/library/doRNG/doc/doRNG.Rnw
/usr/lib64/R/library/doRNG/doc/doRNG.pdf
/usr/lib64/R/library/doRNG/doc/index.html
/usr/lib64/R/library/doRNG/help/AnIndex
/usr/lib64/R/library/doRNG/help/aliases.rds
/usr/lib64/R/library/doRNG/help/doRNG.rdb
/usr/lib64/R/library/doRNG/help/doRNG.rdx
/usr/lib64/R/library/doRNG/help/paths.rds
/usr/lib64/R/library/doRNG/html/00Index.html
/usr/lib64/R/library/doRNG/html/R.css
/usr/lib64/R/library/doRNG/tests/testthat.R
/usr/lib64/R/library/doRNG/tests/testthat/test-doRepro.r
/usr/lib64/R/library/doRNG/tests/testthat/test-dorng-nonattached.r
/usr/lib64/R/library/doRNG/tests/testthat/test-dorng.r
